/**
 * @author ricardo
 */
mlog.translation = {
centschar             : '.',
thousandchar          : ',',
'datasample'          : '2000-01-01\t0.00\tinitial\t\tbank\n2000-01-01\t0.00\tinitial\t\tinvestment\n2000-01-01\t0.00\tinitial\t\twallet\n2000-01-01\t0.00\tinitial\t\tcredit card\n2000-01-01\t0.00\tinitial\tautomobile\t\n2000-01-01\t0.00\tinitial\tbank\t\n2000-01-01\t0.00\tinitial\teducation\t\n2000-01-01\t0.00\tinitial\tincome\t\n2000-01-01\t0.00\tinitial\tentertainment\t\n2000-01-01\t0.00\tinitial\tgrocery\t\n2000-01-01\t0.00\tinitial\thome\t\n2000-01-01\t0.00\tinitial\tothers\t\n2000-01-01\t0.00\tinitial\thealth\t\n2000-01-01\t0.00\tinitial\tclothing\t\n2000-01-01\t0.00\tinitial\tgifts\t\n',
'help text'           : '<h1>Using</h1><h3>Categories and Accounts</h3>As you insert or delete them, the summary will be updated automatically.<h3>Entries</h3><ul><li><span>Date format: Year-Month-Day, 4 digits for year, 2 digits for month and day<br/>e.g. jan, 4 of 2008: 2008-01-04</span></li><li><span>Value: put the negative signal (-) for debits, e.g.: -100,00</span></li><li><span>Description: avoid special characters</span></li><li><span>Category and Account fields: have auto complete support, type any key and a list will be displayed, <b>press ESC key to hide the auto complete list</b>, if necessary</span></li></ul><h3>Editing and Deleting</h3>To delete an entry, press the delete icon <img src="images/delete.png"></img> of it.<br/>Note that the excluded entry will be displayed in the entry input form, to edit or undo your deletion just add the entry again.<h3>Recurring entries</h3>To insert recurring entries, type the data normally, and specify the amount of times in the value field, e.g.:<br/>Annual rent fee of 600,00 (12 times) with due data starting in 2008-01-05<br/><code>date: 2008-01-05<br/>value: -600*12<br/>description: rent fee<br/>category: home<br/>account: bank<br/></code><br/>Note the star signal <b>*</b> meaning times.<br/><br/>Another example would be the purchase of a gift with the value 550,00 divided in 10 times, in the value field type: -550/10<br/><code>date: 2008-01-10<br/>value: -550/10<br/>description: my gift<br/>category: gift<br/>account: credit card<br/></code><br/>10 entries of -55,00 will be made on each day 10.<br/>Beware that some rounding can occur.<h3>Reconcilable entries</h3>To insert a reconcilable entry put a question mark after the date. Until the entry is accepted by pressing the accept icon <img src="images/accept.png"></img> its value will not be considered and its date, if expired, will be the current.<code>date: 2008-01-01?</code><h3>Transfers</h3>To make a transfer, leave the category field empty, when moving to the "from account" a new field will appear: "to account", type the origin and the target in each field, by pressing the add button two entries will be made: a debit and a credit.<h3>Data Editor</h3>Use the data editor feature to edit the text data source, it is very handy in some cases.<br/>Each field is TAB separated, just press apply to save your changes, a backup file with a "old" file extension is generated with the previous data.<h3>Search and Filter</h3>The entries can be easily filtered by typing in the filter field.<br/>To perform advanced filtering, use the regular expression option. <p>Examples:<br/>To filter the "entertainment" entries of December 2007:</p><code>(2007-12).+entertainment</code>Filtering "entertainment" and "gift" entries:<code>(2007-12).+(entertainment|gift)</code><br/><br/><br/>'
};
